spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASSWORD}

server.servlet.context-path=/api
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=60000