spring.application.name=KinoBE

spring.datasource.url=jdbc:mysql://localhost:3306/kinoBE
spring.datasource.username=marco
spring.datasource.password=kode

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true